services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=erpdb
      - POSTGRES_USER=erp_user
      - POSTGRES_PASSWORD=erp_pass
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    environment:
      GUNICORN_CMD_ARGS: "--workers 2 --access-logfile - --error-logfile - --log-level info"
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/health').getcode()==200 else 1)"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        - VITE_API_BASE=http://localhost:8000
    depends_on:
      - backend
    ports:
     - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  db_data: {}